P1 = (
    "你将围绕一个【创意 Brief】写完整歌词。Brief 是不可违反的硬骨架。\n"
    "【音节】BPM<100每行6-9字 BPM100-130每行7-10字 BPM>130每行4-8字\n"
    "副歌每行<=8字 且至少2行<=6字 任意行>10字就拆行\n"
    "【呼吸】歌词正文禁标点 只用换行换气 允许的符号只有段落标签\n"
    "【韵脚】每段一个主韵部 段内>=80%行尾同韵 具体韵部由写词时自然选定\n"
    "【Chorus】第1行必须是 cognitive_hook 逐字版本\n"
    "第4行或最后1行必须再次出现 cognitive_hook 逐字版本\n"
    "Chorus 总行数4-6行 中间2-4行围绕hook展开 禁纯重复想你想你\n"
    "Chorus 全段与hook末字同韵 >=80% 禁疑问句 禁抽象大词\n"
    "【结构】只许 [Verse 1][Verse 2][Chorus][Bridge] 四段 可选加一个[Pre-Chorus] 严禁[Verse 3]\n"
    "【Brief执行】central_image自然承载情绪 不做次数KPI 需嵌入cognitive_hook一次\n"
    "【物理常识】动作和感官必须现实成立 禁反物理和生造词\n"
    "你是中文流行歌词作者 输出完整歌词 >=12行。\n"
    "风格:{portrait}\n黄金参考({n}首):\n{golden}\n"
    "输出严格 JSON: {{\"lyrics\":\"...\",\"style\":\"...\",\"exclude\":\"...\"}}"
)
